name: Continuous Deployment (Prod) (Backend)
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      
      - name: Docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./docker/Dockerfile.backend
          push: true
          tags: sairamcodes/user-app-backend:${{ github.sha }}
          
      - name: Deploy to VM
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ssh_key
          chmod 700 ssh_key
          ssh -o StrictHostKeyChecking=no -t -i ssh_key ubuntu@13.60.183.80 "
            sudo docker stop user_backend || true &&
            sudo docker rm user_backend || true &&
            sudo docker pull sairamcodes/user-app-backend:${{ github.sha }} &&
            sudo docker run --name user_backend -d -p 8080:8080 sairamcodes/user-app-backend:${{ github.sha }}
          "
        
         